### ISSUE TITLE
Store Development  - StoreId not matching

### ISSUE THREAD

**Issue by ThiagoCabral** [ThiagoCabral/Kanban#36]
I just tested the StoreId 1490 and the numbers do not match for Meter 1 and and ENergyChg1

[Issue 1.xlsx](https://github.com/thiagocabral/Kanban/files/1600791/Issue.1.xlsx)

**Comment by jordanedwaaaards** [comment]
GO distinct

**Comment by ThiagoCabral** [comment]
I applied the Distinct to the SQL. 
The number for that Store matches. Now I ran the same SQL for all stores and the numbers to no match for couple store.  Please see the file attached

[Issue 2.xlsx](https://github.com/thiagocabral/Kanban/files/1601104/Issue.2.xlsx)

**Comment by ThiagoCabral** [comment]
@jordanedwaaaards I did update the file with the stores that are not matching.
Please take a look
[Issue 2.2.xlsx](https://github.com/thiagocabral/Kanban/files/1601500/Issue.2.2.xlsx)

**Comment by jordanedwaaaards** [comment]
That’s good news.

Sent from my iPhone

On Jan 3, 2018, at 1:46 PM, thiagocabral <notifications@github.com<mailto:notifications@github.com>> wrote:


@jordanedwaaaards<https://github.com/jordanedwaaaards> I did update the file with the stores that are not matching.
Please take a look
Issue 2.2.xlsx<https://github.com/thiagocabral/Kanban/files/1601500/Issue.2.2.xlsx>

**Comment by ThiagoCabral** [comment]
Please see below the list of the Storeids I am missing form the Fact Table
74116
74125
75342
75350
75372
75381
75382
75384
75387
75414
75415
75417
75418
75428
75429
75434
75444
75446
75465
75582
75591
75619
75622

**Comment by jordanedwaaaards** [comment]
They are there right?!

Sent from my iPhone

On Jan 3, 2018, at 2:06 PM, thiagocabral <notifications@github.com<mailto:notifications@github.com>> wrote:


Please see below the list of the Storeids I am missing form the Fact Table
74116
74125
75342
75350
75372
75381
75382
75384
75387
75414
75415
75417
75418
75428
75429
75434
75444
75446
75465
75582
75591
75619
75622

**Comment by jordanedwaaaards** [comment]
This issue might should be resolved.. we had duplicates between the tables where some were not matching.. brought invoice number and batch number into the fact table so we get all distinct entries.

**Comment by ThiagoCabral** [comment]
All the stores are included in the fact table but the number for couple store still do not match.

Please see the list below

1254 3218 67027 ...

[SU - Testing.xlsx](https://github.com/thiagocabral/Kanban/files/1604497/SU.-.Testing.xlsx)

**Comment by jordanedwaaaards** [comment]
Hey @thiagocabral can you please retest in the morning and let me know if it's still not matching?

I fixed duplicate issue with AcctNumber as far as I can tell.

**Comment by ThiagoCabral** [comment]
Should I add account # as unique too?

Sent from my iPhone

On Jan 4, 2018, at 6:25 PM, jordanedwaaaards <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @thiagocabral<https://github.com/thiagocabral> can you please retest in the morning and let me know if it's still not matching?

I fixed duplicate issue with AcctNumber as far as I can tell.

**Comment by jordanedwaaaards** [comment]
No you shouldn’t have to in the morning

Sent from my iPhone

On Jan 4, 2018, at 6:57 PM, thiagocabral <notifications@github.com<mailto:notifications@github.com>> wrote:

Should I add account # as unique too?

Sent from my iPhone

On Jan 4, 2018, at 6:25 PM, jordanedwaaaards <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Hey @thiagocabral<https://github.com/thiagocabral> can you please retest in the morning and let me know if it's still not matching?

I fixed duplicate issue with AcctNumber as far as I can tell.

**Comment by ThiagoCabral** [comment]
@jordanedwaaaards 
The table still have duplicates.
Last changes:
1) Properchildiid <> 0 for both tables
2) date cutoff is 20160101

**Comment by jordanedwaaaards** [comment]
How about now?

On Jan 5, 2018, at 9:44 AM, thiagocabral <notifications@github.com<mailto:notifications@github.com>> wrote:


@jordanedwaaaards<https://github.com/jordanedwaaaards>
The table still have duplicates.
Last changes:

  1.  Properchildiid <> 0 for both tables
  2.  date cutoff is 20160101

**Comment by ThiagoCabral** [comment]
Fixed!
